### ISSUE TITLE
A zero value for capacity_scaler doesn't work as expect

### ISSUE THREAD

**Issue by devrandom0** [GoogleCloudPlatform/gke-autoneg-controller#153]
Hi,

Having (at least) two different Kubernetes services, pointing to the same backend service, and defining capacity_scaler 0.0 and 1.0 respectively, during the reconciliation loop, it might happen that no changes are detected on the "scaled to 0", when updateBackend is invoked (https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/controllers/autoneg.go#L287), the CapacityScaler field is omitted for them (because of omitempty on the original Backend struct), causing the API to set the [default value](https://cloud.google.com/compute/docs/reference/rest/v1/backendServices) (1).

![Image](https://github.com/user-attachments/assets/16cdb8d1-63a9-46c0-8382-a77dd26f1e5e)

Worth mentioning that there was a similar issue [here](https://github.com/GoogleCloudPlatform/gke-autoneg-controller/issues/108#issuecomment-2061291963).

Example Kubernetes services config:

* Service 1
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{"name":""}}}'
    controller.autoneg.dev/neg: |-
      {
        "backend_services": {
          "80": [
            {
              "name": "app",
              "max_rate_per_endpoint": 10000,
              "capacity_scaler": 100,
              "initial_capacity": 100
            }
          ]
        }
      }
    controller.autoneg.dev/sync: '{"capacity_scaler": true}'
  labels:
    app.kubernetes.io/instance: app1
    app.kubernetes.io/name: httpbin
  name: app1
  namespace: default
spec:
  clusterIP: 10.32.6.19
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: app1
    app.kubernetes.io/name: httpbin
  type: ClusterIP
```

* Service 2
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{"name":""}}}'
    controller.autoneg.dev/neg: |-
      {
        "backend_services": {
          "80": [
            {
              "name": "app",
              "max_rate_per_endpoint": 10000,
              "capacity_scaler": 0,
              "initial_capacity": 100
            }
          ]
        }
      }
    controller.autoneg.dev/sync: '{"capacity_scaler": true}'
  labels:
    app.kubernetes.io/instance: app2
    app.kubernetes.io/name: httpbin
  name: app2
  namespace: default
spec:
  clusterIP: 10.32.6.22
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: app2
    app.kubernetes.io/name: httpbin
  type: ClusterIP
```
