### ISSUE TITLE
Specify non-root user in deployment

### ISSUE THREAD

**Issue by rwkarg** [GoogleCloudPlatform/gke-autoneg-controller#32]
The deployment spec should specify the non-root user in the security context following the #20 change:

```
securityContext:        
  privileged: false        
  allowPrivilegeEscalation: false        
  runAsUser: 1002        
  runAsNonRoot: true
```
