### ISSUE TITLE
Additional pod and container hardening

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/gke-autoneg-controller#94]
We're using the following settings for our deployment --

Container security context:

```yaml
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
```

Pod security context:

```yaml
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

Using these as the default would be useful, as it makes this controller installable into a wider number of clusters (e.g. clusters with restrictive admission controllers)
